name: "GitHub Release & Notification"
description: |
  This action automates GitHub releases:
  - Creates a release for a specified tag (creates the tag if needed)
  - Generates a changelog from merged PRs or commit messages between tags
  - Attaches specified files to the release (optional)
  - Optionally sends a Slack notification to a team channel
  Handles edge cases like missing tags or PRs, and always provides a changelog.
inputs:
  version:
    description: "Release version"
    required: true
  name:
    description: "Project name"
    required: true
  Team_webhook:
    description: "Slack/Webhook URL"
    required: false
  github-token:
    description: "GitHub token"
    required: true
  files:
    description: "List of files to attach to the release (comma-separated)"
    required: false
runs:
  using: "node20"
  main: "dist/index.js"
