name: "GitHub Release & Notification"
description: "Creates a release and sends a team notification"
inputs:
  version:
    description: "Release version"
    required: true
  name:
    description: "Project name"
    required: true
  Team_webhook:
    description: "Slack/Webhook URL"
    required: true
  github-token:
    description: "GitHub token"
    required: true
runs:
  using: "node20"
  main: "dist/index.js"
