name: "GitHub Release & Notification"
description: "Creates a release and sends a team notification"
inputs:
  version:
    description: "Release version"
    required: true
  name:
    description: "Project name"
    required: true
  Team_webhook:
    description: "Slack/Webhook URL"
    required: false
  github-token:
    description: "GitHub token"
    required: true
  files:
    description: "List of files to attach to the release (comma-separated)"
    required: false
runs:
  using: "node20"
  main: "dist/index.js"
